version: '3.8'

services:
  api:
    build: .
    ports:
      - '8090:8090'
    container_name: moneyservice
    image: moneyservice-api
  grafana:
    build: './config/grafana'
    user: '472'
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./config/prometheus:/etc/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
networks:
  monitoring: