version: '3.8'

services:
  api:
    build: .
    ports:
      - '8090:8090'
    container_name: moneyservice
    image: moneyservice-api
  grafana:
#    build: './config/grafana'
    image: grafana/grafana
    user: 'root'
    container_name: customgrafana
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
    expose:
      - 3000
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    #image: prom/prometheus
    build: './prometheus'
    user: 'root'
    container_name: prometheus
    ports:
      - '9090:9090'
#    volumes:
#      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - 9090
#    command:
#      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      monitoring:
        aliases:
          - prometheus
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=true
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    expose:
      - 9200
    networks:
      monitoring:
        aliases:
          - elastic
networks:
  monitoring: